openapi: 3.0.0
info:
  description: "This is the Task Master Api"
  version: 0.0.1
  title: Task Master
paths:
  /:
    get: 
      summary: See Available Services
      operationId: getServices
      responses:
        "200":
          description: "successful operation" 
  /task:
    get:
      summary: "Retrieve Tasks"
      responses:
        "200":
          description: "successful operation"
    post:
      summary: "Create Task"
      requestBody:
        $ref: "#/components/requestBodies/Task"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
  /task/{taskId}:
    get:
      summary: "Retrieve Task By Id"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
        "404":
          description: "task not found"
    put:
      summary: "Update Task By Id"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
        "404":
          description: "task not found"
    delete:
      summary: "Delete Task By Id"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
        "404":
          description: "task not found"
  /user:
    get:
      summary: "List Users (Admin)"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
    post:
      summary: "Create New User"
      requestBody:
        $ref: "#/components/requestBodies/User"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
  /user/{userId}:
    get:
      summary: "Get User Details"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
        "404":
          description: "user not found"
    put:
      summary: "Update User Data"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
    delete:
      summary: "Delete User (Admin)"
      responses:
        "200":
          description: "successful operation"
        "403":
          description: "unauthorized request"
        "404":
          description: "user not found"
components:
  requestBodies:
    User:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateUser"
    Task:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateTask"
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
    CreateUser:
      type: object
      required:
        - username
        - email
      properties:
        username:
          type: string
        email:
          type: string
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        taskDetails:
          type: string
        createdBy:
          type: integer
          format: int64
        assignedTo:
          type: integer
          format: int64
        clonedBy:
          type: integer
          format: int64
        status:
          type: string
          description: Task Status
          enum:
            - Open
            - Closed
        createdDate:
          type: string
          format: date-time
        completedDate:
          type: string
          format: date-time
        dueDate:
          type: string
          format: date-time
        reminder:
          type: string
          format: date-time
    CreateTask:
      type: object
      required:
        - taskDetails
        - createdBy
      properties:
        taskDetails:
          type: string
        createdBy:
          type: integer
          format: int64
        assignedTo:
          type: integer
          format: int64
        clonedBy:
          type: integer
          format: int64
        status:
          type: string
          description: Task Status
          enum:
            - Open
            - Closed
          default: Open
        createdDate:
          type: string
          format: date-time
        completedDate:
          type: string
          format: date-time
        dueDate:
          type: string
          format: date-time
        reminder:
          type: string
          format: date-time
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    

    
